author: R Kash
description: Having a purpose after achieving Financial Independence (FI)
url: https://FIREwithPurpose.com
email: rk@FIREwithPurpose.com
title: "FIRE with Purpose"

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown

header_pages:
  - _pages/homepage.md
  - _pages/about.md
  - _pages/FI Vehicles.md
  - _pages/blog.md

include:
    - _pages
