author: R Kash
description: Having a purpose after achieving Financial Independence (FI)
url: https://FIREwithPurpose.com
email: rk@FIREwithPurpose.com
title: "FIRE with Purpose"

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
